# -*- coding: utf-8 -*-
"""modelo_who_is_who.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b4OgzWNW0tqBQBm7TNBrtusYm1tF-eoQ
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Crear el conjunto de datos completo (Base de conocimiento)
# Se han incluido los 24 personajes de la imagen.
datos = {
    "Personaje": [
        "Toño", "Zac", "Pablo", "Gil", "Beca", "Cori",
        "Gary", "Rogelio", "Pau", "Roy", "Lisa", "Alonso",
        "Oscar", "Erica", "Loren", "Gina", "Olga", "Paco",
        "Anisha", "Laura", "Julio", "Rich", "Kati", "Fer"
    ],
    "Descripcion": [
        "Chico rubio juega baloncesto ropa verde tiene balon", # Toño
        "Chico juega hockey usa casco azul ropa azul tiene stick", # Zac
        "Chico cabello castaño juega esqui ropa amarilla y verde gorro de nieve amarillo", # Pablo
        "Chica cabello castaño juega futbol domina balon ropa azul clara", # Gil
        "Chica rubia juega baloncesto ropa verde tiene balon", # Beca
        "Chica cabello negro atletismo correr ropa roja usa gorra roja", # Cori
        "Chico cabello castaño juega tenis ropa blanca tiene raqueta", # Gary
        "Chico juega baloncesto ropa amarilla tiene balon usa cintillo rojo", # Rogelio
        "Chica cabello negro natacion traje de baño azul usa gafas de buceo", # Pau
        "Chico pelirrojo juega futbol ropa roja tiene balon", # Roy
        "Chica pelo azul juega futbol ropa amarilla usa cintillo tiene balon", # Lisa
        "Chico cabello negro juega golf ropa azul usa visera blanca tiene palo de golf", # Alonso
        "Chico cabello negro juega hockey ropa roja tiene stick", # Oscar
        "Chica cabello castaño juega tenis ropa blanca usa visera tiene raqueta", # Erica
        "Chica rubia juega golf ropa verde usa visera tiene palo de golf", # Loren
        "Chica cabello castaño juega voleibol ropa amarilla usa cintillo azul tiene balon", # Gina
        "Chica pelirroja juega esqui ropa azul usa gorro de nieve azul", # Olga
        "Chico rubio juega tenis ropa roja tiene raqueta", # Paco
        "Chica pelo azul juega golf ropa blanca lleva palos de golf", # Anisha
        "Chica cabello negro juega futbol ropa roja tiene balon", # Laura
        "Chico pelo azul juega futbol ropa blanca tiene balon", # Julio
        "Chico pelirrojo juega baloncesto ropa roja tiene balon", # Rich
        "Chica cabello negro juega esqui ropa amarilla usa gorro de nieve amarillo", # Kati
        "Chica pelirroja juega voleibol ropa blanca usa cintillo tiene balon" # Fer
    ]
}

df = pd.DataFrame(datos)

# 2. Inicializar el modelo de Machine Learning (TF-IDF)
vectorizador = TfidfVectorizer()

# Convertimos nuestras descripciones base en vectores numéricos
matriz_tfidf = vectorizador.fit_transform(df['Descripcion'])

# 3. Función para adivinar el personaje
def adivinar_personaje(descripcion_usuario):
    # Convertir el texto del usuario a vector usando el mismo modelo
    vector_usuario = vectorizador.transform([descripcion_usuario])

    # Calcular la similitud matemática entre el texto del usuario y todos los personajes
    similitudes = cosine_similarity(vector_usuario, matriz_tfidf)

    # Obtener el índice del personaje con la puntuación más alta
    indice_ganador = similitudes.argmax()
    puntuacion = similitudes[0][indice_ganador]

    # Umbral de confianza: si es muy baja, no hay coincidencia clara
    if puntuacion < 0.1:
        return "No estoy seguro, intenta describir más características (deporte, color de pelo, ropa, accesorios)."

    personaje_encontrado = df.iloc[indice_ganador]['Personaje']
    return f"¡Creo que es {personaje_encontrado}! (Nivel de confianza: {puntuacion:.2f})"

# 4. Prueba del sistema (Interacción en Colab)
print("🤖 ¡Hola! Describe a un personaje y adivinaré quién es.")
print("Ejemplo 1: 'Es una chica con pelo azul que juega golf'")
print("Ejemplo 2: 'Chico pelirrojo con ropa roja jugando futbol'")
print("-" * 60)

# Input del usuario (esto generará un cuadro de texto interactivo en Google Colab)
entrada_usuario = input("Describe al personaje: ")

# Ejecutar predicción e imprimir resultado
resultado = adivinar_personaje(entrada_usuario)
print("\nResultado:", resultado)